import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  useWindowDimensions,
} from "react-native";
import { RouteProp, useRoute } from "@react-navigation/native";
import { RootStackParamList } from "../navigation/AppNavigator";
import AudioPlayerControls from "../components/AudioPlayerControls";
import CopyButton from "../components/CopyButton";
import { useAudioPlayer } from "../hooks/useAudioPlayer";

const ReportScreen: React.FC = () => {
  const route = useRoute<RouteProp<RootStackParamList, "Report">>();
  const { transcript, audioUri } = route.params || { transcript: "", audioUri: null };

  const [activeTab, setActiveTab] = useState<"transcription" | "report">("transcription");
  const { isPlaying, duration, position, playPause, seekTo } = useAudioPlayer(audioUri);
  const { width } = useWindowDimensions();

  const reportText = `AI Report: This section simulates a summary generated by an AI model based on the provided transcript.`;

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.tabContainer}>
        <Text
          style={[styles.tab, activeTab === "transcription" && styles.activeTab]}
          onPress={() => setActiveTab("transcription")}
        >
          Transcription
        </Text>
        <Text
          style={[styles.tab, activeTab === "report" && styles.activeTab]}
          onPress={() => setActiveTab("report")}
        >
          Report
        </Text>
      </View>

      {audioUri && (
        <AudioPlayerControls
          isPlaying={isPlaying}
          duration={duration}
          position={position}
          onPlayPause={playPause}
          onSeek={seekTo}
        />
      )}

      <CopyButton text={activeTab === "transcription" ? transcript : reportText} />

      <Text style={[styles.text, { width: width - 40 }]}>
        {activeTab === "transcription" ? transcript : reportText}
      </Text>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 20,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 20,
  },
  tab: {
    marginHorizontal: 20,
    fontSize: 18,
    color: "#888",
  },
  activeTab: {
    color: "#007AFF",
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  text: {
    fontSize: 16,
    lineHeight: 24,
    color: "#333",
    marginTop: 10,
  },
});

export default ReportScreen;
